config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  get '/about', to: 'static_pages#about'
  # CRUD - CREATE, READ, UPDATE, DELETE
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # responsible for showing all pages
  def index
    # local var is only available in the method
    # if we want our view to have access to the var 
    # we need an instance variable
    @pages = Page.all
    # return app/views/pages/index.html.erb
    # render :index
  end
  
  # responsible for showing a specific page
  def show
    @page = Page.find(params[:id])
    # render :show - app/views/pages/show.html.erb
  end

  # responsible for showing a form to edit an exisiting page
  def edit
    @page = Page.find(params[:id])
  end

  # responsible for updating the values of a pre exisiting method
  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      #success
      redirect_to page_path(@page)
    else
      #fail
      render :edit
    end
  end

  # responsoble for showing a form to create a new page
  def new
    @page = Page.new
    # render :new - app/voews/pages/new.html.erb
  end

  #responsible for ssaving a new record in our databases
  def create
    # Strong params
    page = Page.new(page_params)
    # exectues the sql to try to save the new page in the database
    if page.save
      # success - new record in the database
      redirect_to page_path(page)
    else
      # fail - failed to execute the sql for some reason
      render :new
    end
  end

  def destroy
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

  private
    def page_params
      params.require(:page).permit(:title, :author, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    # <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<nav>
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Pages', pages_path %>
</nav>

app/views/pages/edit.html.erb
<h1>Editing: <%= @page.title %>  </h1>
<div>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Title', required: true %>
</div>

<div>
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Author', required: true %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_area :body, placeholder: 'body', required: true %>
</div>

<div>
  <%= f.label :private %>
  <%= f.check_box :private %>
</div>
  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>All Blog Posts</h1>
<%= link_to 'New Blog Post', new_page_path %>
<hr />

<% @pages.each do |page| %>
  <div>

    <h3>
     <%= link_to page.title, page_path(page) %>
    </h3>

    <i>Author: <%= page.author %></i>
    <strong>PRIVATE: <%= page.private ? 'Yes' : 'No' %></strong>
    <%= link_to 'Delete', page_path(page), method: :delete %>
  </div>
  <hr />
<% end %>

app/views/pages/new.html.erb
<h1>Create New Blog Post</h1>

<div>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Title', required: true %>
</div>

<div>
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Author', required: true %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_area :body, placeholder: 'body', required: true %>
</div>

<div>
  <%= f.label :private %>
  <%= f.check_box :private %>
</div>
  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1>
  <%= @page.title %>
</h1>

<i>Author: <%= @page.author %> </i>
<br />
<i>Created: <%= @page.created_at %> </i>

<hr />
<p>
  <%= @page.body %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Back', pages_path %>